### ISSUE TITLE
Doesn't install on my version of Atom

### ISSUE THREAD

**Issue by petonic** [elia/atom-textmate#1]
Here is the stacktrace...  Any ideas?  Do you need more info because there's a conflicting package?

```
undefined method `command' for nil
NoMethodError: undefined method `command' for nil
    at OpalClass.$new (/Users/petonic/.atom/packages/atom-textmate/node_modules/opal/lib/../opal/opal.js:2731:17)
    at NilClass.def.$raise (/Users/petonic/.atom/packages/atom-textmate/node_modules/opal/lib/../opal/opal.js:2383:31)
    at NilClass.def.$method_missing.TMP_1 [as $method_missing] (/Users/petonic/.atom/packages/atom-textmate/node_modules/opal/lib/../opal/opal.js:1834:19)
    at NilClass.method_missing_stub [as $command] (/Users/petonic/.atom/packages/atom-textmate/node_modules/opal/lib/../opal/opal.js:466:35)
    at $TextMate.def.$activate (textmate.rb:205:37)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
The error was thrown from the textmate package.
Create issue on the textmate package

```

**Comment by elia** [comment]
@petonic sorry, should have put a notice on the readme that the repo is not active nor completed.

That said my guess is that the Atom internal api changed since the time I hacked this stuff together

**Comment by elia** [comment]
I closed the issue for the said reason, but feel free to keep writing and asking for stuff here. 
I'll try my best to help 😊

**Comment by petonic** [comment]
No worries. Thanks for the fast confirmation so that I don't spend the next 6 OCD hours of mine trying to fix it. :-)

Sent from Outlook Mobile

On Sun, Mar 6, 2016 at 2:18 PM -0800, "Elia Schito" notifications@github.com wrote:

@petonic sorry, should have put a notice on the readme that the repo is not active nor completed.

That said my guess is that the Atom internal api changed since the time I hacked this stuff together

**Comment by elia** [comment]
> Thanks for the fast confirmation so that I don't spend the next 6 OCD hours of mine trying to fix it. :-)

LOL :D
